package Leetcode;

public class Diffrence_String {
    public static void main(String[] args) {
        String s =  "abcd", t = "abcde";
        System.out.println(test(s,t));
    }
    public static char test(String s, String t ){
        int sum1 =0;
        int sum2 =0;
        for(int i =0;i<s.length();i++){
            sum1+=s.charAt(i);
        }
        for(int j =0;j<t.length();j++){
            sum2+=t.charAt(j);
        }
        return(char) (sum2-sum1);
    }
}


/*
389. Find the Difference
Easy
3.6K
411
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */